# Permalinks
plugins: [jekyll-paginate]
gems:
  - jekyll-pagination
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Setup
title: defwdahyun0, 개발 일지
baseurl: ""
url: "https://defwdahyun0.github.io"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: dahyun
  url: https://defwdahyun0.github.io
  email: wdh112139@gmail.com
  github: defwdahyun0
  google_analytics: G-86WEDG64TH

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/codeFabian/codeFabian.github.io

version: 2.0.0
github:
  repo: https://github.com/defwdahyun0/defwdahyun0.github.io